version: '3'

services:
  web:
    container_name: courseCatalog
    image: IMAGE
    ports:
      - 5000:5000
    depends_on:
      - 'mariadb'
      - 'web_initiate_db'

  web_initiate_db:
    container_name: courseCatalog_init_db
    image: IMAGE
    entrypoint: ["python3","create_db.py"]
    depends_on:
    - 'mariadb'

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123qwe"
    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:
